version: '2'

services:
  ci_master:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:
    driver: local     
